import Head from 'next/head';
import React, { useRef, useState } from 'react';
import HomeComponent from '../components/HomeComponent';

function Home() {
  const storiesRef = useRef();
  const [prev1, setPrev1] = useState(false);
  const [next1, setNext1] = useState(false);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeComponent {...{ storiesRef, prev1, next1, setPrev1, setNext1 }} />
    </div>
  );
}

export default Home;
